### ISSUE TITLE
Not displaying github username while hovering over avatar in Recent Contributors section

### ISSUE THREAD

**Issue by govindgoel** [publiclab/community-toolbox#331]
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
It should show the github username while hovering over recent contributors list

### Please show us where to look
https://code.publiclab.org/ ...

![ ](https://media.giphy.com/media/YR2oNZKIRfg9kRCsdi/giphy.gif)
> This can help us diagnose the issue: 

### Browser, version, and operating system
Brave Browser Version 1.1.21 Chromium: 79.0.3945.79 (Official Build) (64-bit)
Firefox Browser Version 71.0 (64-bit)
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by govindgoel** [comment]
I will work on this

**Comment by govindgoel** [comment]
I have fixed the issue On which branch I should make a pr.

**Comment by Rishabh570** [comment]
Hi @govindgoel, You can work on a new branch and open the PR against "main" branch.
Thanks!

**Comment by DevanshCodes** [comment]
Hey @govindgoel @Rishabh570 I fixed the exact same issue and my PR got merged. Here's the link: https://github.com/publiclab/community-toolbox/pull/329. Thanks :)

**Comment by govindgoel** [comment]
Hi @DevanshCodes  You can check the live[ website](https://code.publiclab.org) over the recent contributors section and have a look at the issue or in the above GIF.

**Comment by govindgoel** [comment]
@DevanshCodes @Rishabh570  When i build after doing changes in src folder using grunt build it is showing so many changes although I changed only one line.What should I do.

**Comment by govindgoel** [comment]
May I send changes in the PR in recentContributorsUI.js only.

**Comment by Rishabh570** [comment]
Hi @govindgoel, it seems like the issue is already fixed in @DevanshCodes's PR. The changes are not pushed to the live version yet that's why you are seeing that issue. Sorry, I was not aware. Thanks for reporting the issue though :+1: 

I think this issue should be closed now.

**Comment by govindgoel** [comment]
@Rishabh570  But he has not changed for the recent contributors section in his patch It will still not show the github username while hovering over avatar in that section.

**Comment by Rishabh570** [comment]
Oh, yes it doesn't have the `title` attr. Is there any PR of yours regarding this, we would love to fix this.
